// Objective-C API for talking to pi Go package.
//   gobind -lang=objc pi
//
// File is generated by gobind. Do not edit.

#ifndef __Pi_H__
#define __Pi_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"


@class PiAndroidPoint;
@class PiPlatformInterface;
@class PiProtectedDialer;
@protocol PiAndroidVPNService;
@class PiAndroidVPNService;
@protocol PiApplePrinter;
@class PiApplePrinter;

@protocol PiAndroidVPNService <NSObject>
- (long)setup:(NSString* _Nullable)Conf;
- (BOOL)vpnProtect:(long)p0;
@end

@protocol PiApplePrinter <NSObject>
- (void)applePrint:(NSString* _Nullable)log;
@end

@interface PiAndroidPoint : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
/**
 * NewAndroidPoint new AndroidPoint
 */
- (nullable instancetype)init:(id<PiAndroidVPNService> _Nullable)s adns:(BOOL)adns;
@property (nonatomic) id<PiAndroidVPNService> _Nullable supportSet;
// skipped field AndroidPoint.Vpoint with unsupported type: *github.com/xtls/xray-core/core.Instance

@property (nonatomic) BOOL isRunning;
@property (nonatomic) BOOL asyncResolve;
@property (nonatomic) PiPlatformInterface* _Nullable vInterface;
- (int64_t)queryStatistics:(NSString* _Nullable)tag direct:(NSString* _Nullable)direct;
- (void)setConfiguration:(NSString* _Nullable)configuration node:(NSString* _Nullable)node;
/**
 * RunLoop Run V2Ray main loop
 */
- (BOOL)startVPN:(NSString* _Nullable)url error:(NSError* _Nullable* _Nullable)error;
/**
 * StopLoop Stop V2Ray main loop
 */
- (BOOL)stopVPN:(NSError* _Nullable* _Nullable)error;
- (void)writeIPPacket:(NSData* _Nullable)ipPacket length:(long)length;
@end

@interface PiPlatformInterface : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) id<PiAndroidVPNService> _Nullable supportSet;
- (BOOL)sync:(NSError* _Nullable* _Nullable)error;
- (BOOL)vpnProtect:(long)v;
- (BOOL)write:(NSData* _Nullable)p0 n:(long* _Nullable)n error:(NSError* _Nullable* _Nullable)error;
- (void)xWrite:(long)xtype message:(NSString* _Nullable)message;
@end

/**
 * ProtectedDialer ...
 */
@interface PiProtectedDialer : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
// skipped method ProtectedDialer.DestIpAddress with unsupported parameter or return types

// skipped method ProtectedDialer.Dial with unsupported parameter or return types

- (BOOL)isVServerReady;
// skipped method ProtectedDialer.PrepareDomain with unsupported parameter or return types

- (void)prepareResolveChan;
// skipped method ProtectedDialer.ResolveChan with unsupported parameter or return types

- (BOOL)vpnProtect:(long)p0;
@end

FOUNDATION_EXPORT NSString* _Nonnull PiChangeURL(NSData* _Nullable configuration, NSString* _Nullable payload);

FOUNDATION_EXPORT NSString* _Nonnull PiGetUsing(void);

FOUNDATION_EXPORT NSString* _Nonnull PiGetV2Env(void);

FOUNDATION_EXPORT NSString* _Nonnull PiGetVersion(void);

/**
 * InitV2Env set v2 asset path
 */
FOUNDATION_EXPORT void PiInitV2Env(NSString* _Nullable envPath);

/**
 * NewAndroidPoint new AndroidPoint
 */
FOUNDATION_EXPORT PiAndroidPoint* _Nullable PiNewAndroidPoint(id<PiAndroidVPNService> _Nullable s, BOOL adns);

FOUNDATION_EXPORT NSString* _Nonnull PiParse(NSString* _Nullable uri);

FOUNDATION_EXPORT int64_t PiQueryStatistics(NSString* _Nullable tag, NSString* _Nullable direct);

FOUNDATION_EXPORT void PiSetApplePrinter(id<PiApplePrinter> _Nullable p0);

FOUNDATION_EXPORT void PiSetTimeout(long timeout);

// skipped function StartInstance with unsupported parameter or return types


FOUNDATION_EXPORT NSString* _Nonnull PiStartVPN(NSData* _Nullable configuration, NSString* _Nullable url);

FOUNDATION_EXPORT void PiStopVPN(void);

@class PiAndroidVPNService;

@class PiApplePrinter;

/**
 * AndroidVPNService To support Android VPN mode
 */
@interface PiAndroidVPNService : NSObject <goSeqRefInterface, PiAndroidVPNService> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (long)setup:(NSString* _Nullable)Conf;
- (BOOL)vpnProtect:(long)p0;
@end

@interface PiApplePrinter : NSObject <goSeqRefInterface, PiApplePrinter> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (void)applePrint:(NSString* _Nullable)log;
@end

#endif
